path_key: test # Choice. Only files with 'test' in their name in the input directory will be processed.


keys:
  target: gt
  pred: pred

metrics:

  clip_image_to_image_score: # custom test name
      metric:
        class: src.metric.clip_score.ClipScore
        clip_model: openai/clip-vit-base-patch16
        device: cuda

  clip_image_to_text_score:
    metric:
      class: src.metric.clip_score.ClipScore
      clip_model: openai/clip-vit-base-patch16
      device: cuda
    special_keys: # custom key
       - prompt
       - pred
    special_input_paths:
      - example_data/example_data.json
    just_special_input_paths: true # if true, only the special_input_paths will be used
    
  ssim: 
    metric:  # metric class
      class: src.metric.ssim.SSIM
      device: cuda
    
  psnr_score:
    metric:
      class: src.metric.psnr.PSNR
      device: cuda

  lipis_score:
    metric:
      class: src.metric.lpips.LPIPS
      device: cuda




